# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pingback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(choices=[('pypi', 'PyPI')], default='pypi', max_length=12)),
                ('package_name', models.CharField(max_length=256)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PingbackIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('pingback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingback.Pingback')),
            ],
        ),
    ]
