# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingback', '0003_auto_20170914_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingback',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pingback',
            name='first_seen_blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
